# Generated by Django 6.0.6 on 2026-07-18 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0011_subscriptionprice_timestampt_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionprice',
            options={'ordering': ['order', 'featured', '-updated']},
        ),
        migrations.RenameField(
            model_name='subscriptionprice',
            old_name='timestampt',
            new_name='timestamp',
        ),
    ]
