# Generated by Django 6.0.6 on 2026-07-23 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0014_alter_subscriptionprice_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionprice',
            name='features',
            field=models.TextField(blank=True, help_text='Features for pricing,\n        seperated by a new line ', null=True),
        ),
    ]
