# Generated by Django 6.0.6 on 2026-07-23 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0015_subscriptionprice_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionprice',
            name='features',
            field=models.TextField(blank=True, help_text=' Features for pricing', null=True),
        ),
    ]
