# Generated by Django 6.0.5 on 2026-07-28 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0017_remove_subscriptionprice_features_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionprice',
            options={'ordering': ['subscription__order', 'order', '-updated']},
        ),
    ]
